// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCGnraO6-pGEYYYguKPPr5ORIj7yBg9Fh4',
    appId: '1:363460925869:web:db41b1ef72f1f702766924',
    messagingSenderId: '363460925869',
    projectId: 'crud-firestore-2a3b9',
    authDomain: 'crud-firestore-2a3b9.firebaseapp.com',
    storageBucket: 'crud-firestore-2a3b9.appspot.com',
    measurementId: 'G-2YC0EKR53L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnoe486ZRgWA2o_p-PK-rUBkIWQulVIAw',
    appId: '1:363460925869:android:16e346d69c74a803766924',
    messagingSenderId: '363460925869',
    projectId: 'crud-firestore-2a3b9',
    storageBucket: 'crud-firestore-2a3b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF-RWbG9Mg-bsDnMA6suTSUN0fZDDZAwg',
    appId: '1:363460925869:ios:8f2fecc44b82b267766924',
    messagingSenderId: '363460925869',
    projectId: 'crud-firestore-2a3b9',
    storageBucket: 'crud-firestore-2a3b9.appspot.com',
    iosBundleId: 'com.example.firestore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCF-RWbG9Mg-bsDnMA6suTSUN0fZDDZAwg',
    appId: '1:363460925869:ios:8f2fecc44b82b267766924',
    messagingSenderId: '363460925869',
    projectId: 'crud-firestore-2a3b9',
    storageBucket: 'crud-firestore-2a3b9.appspot.com',
    iosBundleId: 'com.example.firestore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCGnraO6-pGEYYYguKPPr5ORIj7yBg9Fh4',
    appId: '1:363460925869:web:2234a0c4d70d1f10766924',
    messagingSenderId: '363460925869',
    projectId: 'crud-firestore-2a3b9',
    authDomain: 'crud-firestore-2a3b9.firebaseapp.com',
    storageBucket: 'crud-firestore-2a3b9.appspot.com',
    measurementId: 'G-Z0702T3LBK',
  );
}
